# Feature Engineering Pipeline
### AI & ML Engineering Bootcamp - Day 4

## Importing the Required Library

In [4]:
import pandas as pd

df = pd.read_csv("retail_sales_dataset.csv")
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

## Datetime Feature Extraction

In [5]:
df["Date"] = pd.to_datetime(df["Date"])

df["Month"] = df["Date"].dt.month
df["DayOfWeek"] = df["Date"].dt.day_name()
df["Is_Weekend"] = df["DayOfWeek"].isin(["Saturday", "Sunday"])

## Displaying the First Five Rows

In [6]:
categorical_columns = df.select_dtypes(include="object").columns.tolist()
categorical_columns

C:\Users\cc\AppData\Local\Temp\ipykernel_16264\2020219167.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns.tolist()

['Customer ID', 'Gender', 'Product Category', 'DayOfWeek']

## Exploring the Dataset Structure

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[us]
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
 9   Month             1000 non-null   int32
 10  DayOfWeek         1000 non-null   str
 11  Is_Weekend        1000 non-null   bool
dtypes: bool(1), datetime64[us](1), int32(1), int64(5), str(4)
memory usage: 83.1 KB

In [8]:
df.columns

Index(['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age',
       'Product Category', 'Quantity', 'Price per Unit', 'Total Amount',
       'Month', 'DayOfWeek', 'Is_Weekend'],
      dtype='str')

## Viewing Dataset Columns

In [9]:
print(df.columns.tolist())

['Transaction ID', 'Date', 'Customer ID', 'Gender', 'Age', 'Product Category', 'Quantity', 'Price per Unit', 'Total Amount', 'Month', 'DayOfWeek', 'Is_Weekend']

In [10]:
df.select_dtypes(include="object")

C:\Users\cc\AppData\Local\Temp\ipykernel_16264\755674511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

    Customer ID  Gender Product Category  DayOfWeek
0       CUST001    Male           Beauty     Friday
1       CUST002  Female         Clothing     Monday
2       CUST003    Male      Electronics     Friday
3       CUST004    Male         Clothing     Sunday
4       CUST005    Male           Beauty   Saturday
..          ...     ...              ...        ...
995     CUST996    Male         Clothing    Tuesday
996     CUST997    Male           Beauty     Friday
997     CUST998  Female           Beauty     Sunday
998     CUST999  Female      Electronics    Tuesday
999    CUST1000    Male      Electronics  Wednesday

[1000 rows x 4 columns]

In [11]:
df.select_dtypes(include="object").columns

C:\Users\cc\AppData\Local\Temp\ipykernel_16264\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['Customer ID', 'Gender', 'Product Category', 'DayOfWeek'], dtype='str')

## Identifying Categorical Columns

In [12]:
categorical_columns = df.select_dtypes(include="object").columns.tolist()

categorical_columns

C:\Users\cc\AppData\Local\Temp\ipykernel_16264\349536094.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns.tolist()

['Customer ID', 'Gender', 'Product Category', 'DayOfWeek']

## Applying One-Hot Encoding

In [13]:
df = pd.get_dummies(
    df,
    columns=categorical_columns,
    drop_first=True
)

## Preview of the Encoded Dataset

In [14]:
df.head()

,Transaction ID,Date,Age,Quantity,Price per Unit,Total Amount,Month,Is_Weekend,Customer ID_CUST002,Customer ID_CUST003,...,Customer ID_CUST999,Gender_Male,Product Category_Clothing,Product Category_Electronics,DayOfWeek_Monday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,1,2023-11-24,34,3,50,150,11,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,2,2023-02-27,26,2,500,1000,2,False,True,False,...,False,False,True,False,True,False,False,False,False,False
2,3,2023-01-13,50,1,30,30,1,False,False,True,...,False,True,False,True,False,False,False,False,False,False
3,4,2023-05-21,37,1,500,500,5,True,False,False,...,False,True,True,False,False,False,True,False,False,False
4,5,2023-05-06,30,2,50,100,5,True,False,False,...,False,True,False,False,False,True,False,False,False,False

## Verifying the Machine Learning Ready Dataset

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 1016 entries, Transaction ID to DayOfWeek_Wednesday
dtypes: bool(1009), datetime64[us](1), int32(1), int64(5)
memory usage: 1.0 MB

In [16]:
df.select_dtypes(include="object").columns

Index([], dtype='str')

## Checking the Final Dataset Shape

In [17]:
df.shape

(1000, 1016)

## Exporting the Final Dataset

In [18]:
df.to_csv("model_ready_features.csv", index=False)

print("model_ready_features.csv has been created successfully.")

model_ready_features.csv has been created successfully.